import {WithoutStyle} from "@miniskylab/antimatter-framework";
import {IconStyle} from "@miniskylab/antimatter-icon";
import {TextStyle} from "@miniskylab/antimatter-text";
import {ViewStyle} from "@miniskylab/antimatter-view";
import {SimpleWeatherData, TimeFrameForecastData} from "../components";
import {WeatherWidgetProps} from "./props";

export type WeatherWidgetStyle = (weatherWidgetProps: WithoutStyle<WeatherWidgetProps>) => {
    Root: ViewStyle;
    StatusBar: ViewStyle;
    StatusContainer: ViewStyle;
    StatusIcon: IconStyle;
    StatusValue: TextStyle;
    WeatherConditionContainer: ViewStyle;
    WeatherConditionIcon: IconStyle;
    WeatherConditionLabel: TextStyle;
    MainContainer: ViewStyle;
    FeelsLikeContainer: ViewStyle;
    FeelsLikeLabel: TextStyle;
    FeelsLikeValue: TextStyle;
    TemperatureRangeValueContainer: ViewStyle;
    TemperatureRangeMinValue: TextStyle;
    TemperatureRangeCurrentValue: TextStyle;
    TemperatureRangeMaxValue: TextStyle;
    TemperatureRangeHr: ViewStyle;
    TemperatureRangeLabelContainer: ViewStyle;
    TemperatureRangeMinLabel: TextStyle;
    TemperatureRangeCurrentLabel: TextStyle;
    TemperatureRangeMaxLabel: TextStyle;
    ShortWeatherDataContainer: ViewStyle;
    UvIndexIcon: IconStyle;
    UvIndexDescription: TextStyle;
    WindIcon: IconStyle;
    WindSpeed: TextStyle;
    SimpleWeatherData1: SimpleWeatherData.Style;
    SimpleWeatherData2: SimpleWeatherData.Style;
    SimpleWeatherData3: SimpleWeatherData.Style;
    TimeFrameForecastDataContainer: ViewStyle;
    TimeFrameForecastData: TimeFrameForecastData.Style;
};
