import {WithoutStyle} from "@miniskylab/antimatter-framework";
import {IconStyle} from "@miniskylab/antimatter-icon";
import {LabelStyle} from "@miniskylab/antimatter-label";
import {ViewStyle} from "@miniskylab/antimatter-view";
import {SimpleWeatherData} from "../components";
import {WeatherWidgetProps} from "./props";

export type WeatherWidgetStyle = (weatherWidgetProps: WithoutStyle<WeatherWidgetProps>) => {
    Root: ViewStyle;
    StatusBar: ViewStyle;
    StatusContainer: ViewStyle;
    StatusIcon: IconStyle;
    StatusValue: LabelStyle;
    WeatherConditionContainer: ViewStyle;
    WeatherConditionIcon: IconStyle;
    WeatherConditionLabel: LabelStyle;
    MainContainer: ViewStyle;
    TemperatureRangeValueContainer: ViewStyle;
    TemperatureRangeValue: LabelStyle;
    TemperatureRangeHr: ViewStyle;
    TemperatureRangeLabelContainer: ViewStyle;
    TemperatureRangeLabel: LabelStyle;
    FeelsLikeContainer: ViewStyle;
    FeelsLikeLabel: LabelStyle;
    FeelsLikeValue: LabelStyle;
    ShortWeatherDataContainer: ViewStyle;
    UvIndexIcon: IconStyle;
    UvIndexDescription: LabelStyle;
    WindIcon: IconStyle;
    WindSpeed: LabelStyle;
    SimpleWeatherData: SimpleWeatherData.Style;
};
