import {FontDisplay} from "expo-font";
import {useCustomFonts} from "../../hooks";
import {IcomoonSettings} from "../types";
import glyph from "./glyph.ttf";
import selection from "./selection.json";

export function useDefaultIconSet(): IcomoonSettings
{
    const [fontLoaded] = useCustomFonts({glyph: {uri: glyph, display: FontDisplay.FALLBACK}});
    return [fontLoaded, selection, "glyph", "glyph.ttf"];
}

export enum DefaultIconSet
{
    None = "none",
    ChevronLeft = "chevron-left",
    ChevronDown = "chevron-down",
    ChevronUp = "chevron-up",
    ChevronRight = "chevron-right",
    CheckMark = "check-mark",
    Info = "info",
    Flag = "flag",
    Briefcase = "briefcase",
    Graduation = "graduation",
    Clock = "clock",
    History = "history",
    Location = "location",
    Pen = "pen",
    Rocket = "rocket",
    Medal = "medal",
    Origin = "origin",
    NoMic = "no-mic",
    Warning = "warning",
    Heart = "heart",
    Sun = "sun",
    Moon = "moon",
    YinYang = "yin-yang",
    TrashCan = "trash-can",
    XMark = "x-mark",
    PlusCircle = "plus-circle",
    Antimatter = "antimatter",
    ArrowLeft = "arrow-left",
    ArrowRight = "arrow-right",
    ArrowUp = "arrow-up",
    ArrowDown = "arrow-down",
    ReactJs = "react-js",
    MySql = "mysql",
    DotNet = "dotnet",
    Dna = "dna",
    StackOverflow = "stack-overflow",
    MiniSkyLab = "miniskylab",
    NewTab = "new-tab",
    Download = "download",
    Calendar = "calendar",
    WiFi = "wifi",
    Document = "document",
    FloppyDisk = "floppy-disk",
    XMarkInsideCircle = "x-mark-inside-circle",
    Eye = "eye",
    Quill = "quill",
    Fire = "fire",
    NotAllowed = "not-allowed",
    Apple = "apple",
    GasStation = "gas-station",
    Plane = "plane",
    Lightning = "lightning",
    Droplet = "droplet",
    Group = "group",
    Road = "road",
    Basket = "basket",
    Money = "money",
    PriceTag = "price-tag",
    LockInsideShield = "lock-inside-shield",
    User = "user",
    Lock = "lock",
    Health = "health",
    Statistics = "statistics",
    Circle = "circle",
    Home = "home",
    Gear = "gear",
    Fairshare = "fairshare",
    Registry = "registry",
    Umbrella = "umbrella",
    Direction = "direction",
    UvIndex = "uv-index",
    AirQualityIndex = "air-quality-index"
}
