export * from "../../variants";
export * from "./outlined-circular-coral";
export * from "./outlined-circular-gigantic";
export * from "./outlined-circular-large";
export * from "./outlined-rectangular-tomato";
export * from "./solid-rectangular-gigantic";
export * from "./solid-rectangular-large";
export * from "./solid-rectangular-green";
export * from "./solid-rectangular-gold";
